export const FETCH_MOVIES = 'FETCH_MOVIES';
export const FETCH_CHARACTER = 'FETCH_CHARACTER';
export const CLEAR_CHARACTERS = 'CLEAR_CHARACTERS';
export const FILTERED_CHARACTERS = 'FILTERED_CHARACTERS';